/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as ProtectedMyMoviesIndexRouteImport } from './routes/_protected/my-movies/index'
import { Route as ProtectedExploreIndexRouteImport } from './routes/_protected/explore/index'
import { Route as ProtectedMyMoviesNewIndexRouteImport } from './routes/_protected/my-movies/new/index'

const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ProtectedMyMoviesIndexRoute = ProtectedMyMoviesIndexRouteImport.update({
  id: '/my-movies/',
  path: '/my-movies/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedExploreIndexRoute = ProtectedExploreIndexRouteImport.update({
  id: '/explore/',
  path: '/explore/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedMyMoviesNewIndexRoute =
  ProtectedMyMoviesNewIndexRouteImport.update({
    id: '/my-movies/new/',
    path: '/my-movies/new/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/explore': typeof ProtectedExploreIndexRoute
  '/my-movies': typeof ProtectedMyMoviesIndexRoute
  '/my-movies/new': typeof ProtectedMyMoviesNewIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/explore': typeof ProtectedExploreIndexRoute
  '/my-movies': typeof ProtectedMyMoviesIndexRoute
  '/my-movies/new': typeof ProtectedMyMoviesNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_protected/explore/': typeof ProtectedExploreIndexRoute
  '/_protected/my-movies/': typeof ProtectedMyMoviesIndexRoute
  '/_protected/my-movies/new/': typeof ProtectedMyMoviesNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/sign-in'
    | '/sign-up'
    | '/explore'
    | '/my-movies'
    | '/my-movies/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/sign-in' | '/sign-up' | '/explore' | '/my-movies' | '/my-movies/new'
  id:
    | '__root__'
    | '/_auth'
    | '/_protected'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_protected/explore/'
    | '/_protected/my-movies/'
    | '/_protected/my-movies/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_protected/my-movies/': {
      id: '/_protected/my-movies/'
      path: '/my-movies'
      fullPath: '/my-movies'
      preLoaderRoute: typeof ProtectedMyMoviesIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/explore/': {
      id: '/_protected/explore/'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ProtectedExploreIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/my-movies/new/': {
      id: '/_protected/my-movies/new/'
      path: '/my-movies/new'
      fullPath: '/my-movies/new'
      preLoaderRoute: typeof ProtectedMyMoviesNewIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface ProtectedRouteRouteChildren {
  ProtectedExploreIndexRoute: typeof ProtectedExploreIndexRoute
  ProtectedMyMoviesIndexRoute: typeof ProtectedMyMoviesIndexRoute
  ProtectedMyMoviesNewIndexRoute: typeof ProtectedMyMoviesNewIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedExploreIndexRoute: ProtectedExploreIndexRoute,
  ProtectedMyMoviesIndexRoute: ProtectedMyMoviesIndexRoute,
  ProtectedMyMoviesNewIndexRoute: ProtectedMyMoviesNewIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
